### ISSUE TITLE
Could you explain how it treats its path or change it for debug.traceback()?

### ISSUE THREAD

**Issue by ZwerOxotnik** [JanSharp/phobos#4]
(This message as an example, with https://github.com/ZwerOxotnik/zk-lib and https://github.com/ClaudeMetz/AssemblyAnalyst/blob/master/modfiles/data.pho )
`log(debug.traceback())`
```
stack traceback:  
__zk-lib__/experimental/lazyAPI.lua:1161: in function 'get_current_mod'  
__zk-lib__/experimental/lazyAPI.lua:1058: in function 'extend'  
data.pho:3: in main chunk  
(...tail calls...)
```

I expected to see `__assemblyanalyst__/data` etc.

I don't really understand why it has such path in the traceback now.

**Comment by ZwerOxotnik** [comment]
@JanSharp (this ping to ensure you got a ping at least once)

**Comment by JanSharp** [comment]
That's because you can choose to put whatever you want as the "source" name of a function into Lua bytecode. Phobos `0.1.x` is currently tedious to use/setup and it seems like Therenas didn't set it up to add the mod name prefix to the source name, which would be done by adding `--source-name "@__assemblyanalyst__/?"` when compiling using Phobos.

This should be less of an issue once build profiles are a thing and I can provide templates for Factorio mods, unfortunately it's taking its time.

I'm curious how exactly you encountered this though, mostly to determine if it's worth bothering Therenas asking for a recompile for that ;)

**Comment by ZwerOxotnik** [comment]
> I'm curious how exactly you encountered this though

It crashed my mod, because my mod relies on \``debug.traceback()`\`

> `--source-name "@__assemblyanalyst__/?"`

Well, how about checking `name` in info.json for major files like ``data.lua` `` etc?

**Comment by JanSharp** [comment]
> It crashed my mod, because my mod relies on `debug.traceback()`

A production mod relying on the debug library and debug symbols isn't great. However in order to prevent these issues from happening again I'd suggest handling all possible debug symbols, since like I said anything could be in there, Phobos is probably just the first tool that enables you to do it.

I wouldn't use traceback because its output is not machine readable, it's human readable. Looking at Lua source it's using `short_src`, which makes it hard to tell where the code came from. Specifically it makes it impossible to distinguish between file name sources or literal "labeled" sources ([this code converts source into short_src](https://github.com/Rseding91/Factorio-Lua/blob/master/src/lobject.c#L254-L288)).

So my proposal is to use get_info instead, the only downside is that caching is difficult/impossible.
But I've gone ahead and implemented it:

```lua
---transcribed from lauxlib.c:101: countlevels
local function count_levels()
  local li = 1
  local le = 1
  -- find an upper bound
  while debug.getinfo(le, "t") do
    li = le
    le = le * 2
  end
  -- do a binary search
  while li < le do
    local m = math.floor((li + le) / 2)
    if debug.getinfo(m, "t") then
      li = m + 1
    else
      le = m
    end
  end
  return le - 2 -- idk why this needs a -2 instead of -1, but it do
end

---gets the first (entry) function on the stack that isn't a C function and isn't a tail call
---@param what infowhat? @ must contain "S" and "t". default: "St".
---Once an appropriate function is found it returns the table from getinfo using this `what`
---@return debuginfo @ I think this can be nil if every single call was a tail call from the beginning,
---including the call to this function. So basically never
local function get_first_lua_func_info(what)
  what = what or "St"
  local level = count_levels()
  while true do
    local info = debug.getinfo(level, what)
    if not info.istailcall and info.what ~= "C" then
      return info
    end
    level = level - 1
    -- level 0 will always be the getinfo C function itself, no need to check it, just return
    if level == 0 then break end
  end
end

---@return 1|2|3|4 @ 1: data, 2: data-updates, 3: data-final-fixes, 4: unknown
local function get_stage()
  local info = get_first_lua_func_info()
  -- must start with an @ which indicates that it is a file name
  if not info.source:find("^@") then
    return 4
  end

  -- %f[^/\0] is a frontier pattern matching anywhere right past a / or at the beginning of the string
  -- extra non escaped dot at the end to make sure the file has any extension
  if info.source:find("%f[^/\0]data%..") then
    return 1
  elseif info.source:find("%f[^/\0]data%-updates%..") then
    return 2
  elseif info.source:find("%f[^/\0]data%-final%-fixes%..") then
    return 3
  else
    return 4
  end
end

---@return string @ `"?"` if it couldn't find a mod name
local function get_current_mod()
  local info = get_first_lua_func_info()
  -- spaces in mod names for legacy support
  return info.source:match("^@__([a-zA-Z0-9 _-]-)__") or "?"
end
```

And lastly, I will talk with Therenas about it, it shouldn't take much time.

> Well, how about checking name in `info.json` for major files like `data.lua` etc?

This is something I thought of for a Factorio build profile template. Which means it wouldn't always do that, because Phobos isn't made just for Factorio. This also means that right now in `0.1.x` it's not viable because it would still require the user to provide some command line argument telling it "hey this is for Factorio", and it would introduce way too many edge cases, mostly revolving around finding the `info.json` file. I'm really hoping I can get out of the `0.1.x` usability hell soon.

**Comment by ZwerOxotnik** [comment]
It didn't work for assemblyanalyst properly, I'll check again and more (a bit) later.  

```lua
stack traceback:
__zk-lib__/experimental/lazyAPI.lua:1214: in function 'get_current_mod'
__zk-lib__/experimental/lazyAPI.lua:1055: in function 'extend'
data.pho:3: in main chunk
(...tail calls...)
```

```lua
{
 istailcall = false,
 lastlinedefined = 1078,
 linedefined = 1029,
 short_src = "__zk-lib__/experimental/lazyAPI.lua",
 source = "@__zk-lib__/experimental/lazyAPI.lua",
 what = "Lua"
}
```
However, `return le - 1` gives this:
```
{
  istailcall = true,
  lastlinedefined = 0,
  linedefined = 0,
  short_src = "data.pho",
  source = "@data.pho",
  what = "main"
}
```

**Comment by JanSharp** [comment]
huh, I guess I must have messed something up when testing. If -1 works then that's good

**Comment by ZwerOxotnik** [comment]
Um, I don't think so, because it means there are 2 cases because of precompiled chunks and not precompiled chunks. However, I'm not sure how to distinguish it with this method yet/still.

**Comment by ZwerOxotnik** [comment]
I'll check it again.

**Comment by ZwerOxotnik** [comment]
Hm, good news, it'll return nil with \``return le - 1` for not precompiled chunks

**Comment by JanSharp** [comment]
alright so I figured out why the extra -1 was needed, it's because count_levels is also a function on the stack, which means as soon as it returns there's one function less.
However I wasn't able to reproduce the _exact_ behavior you were talking about, because what I'm testing is having a tail call in the main chunk vs not and it works. what you're calling a precompiled chunk is basically just a tail call in the main chunk, since that is what the generated Phobos "bytecode" file does.

In the process of testing this I've decided to actually think about and understand the binary search and I've changed it because what I've transcribed from Lua source doesn't make sense in my head. So just in case that was the issue, could you try with this now?:
```lua
  -- do a binary search
  while li < (le - 1) do
    local m = math.floor((li + le) / 2)
    if debug.getinfo(m, "t") then
      li = m
    else
      le = m
    end
  end
  return li - 1
```

**Comment by ZwerOxotnik** [comment]
Ah, yeah, that case didn't work for you, because it's a tail call.

**Comment by JanSharp** [comment]
No worries, keep me posted :)

**Comment by ZwerOxotnik** [comment]
Should I dump the whole info from all levels in both cases?

**Comment by JanSharp** [comment]
I suppose, it might help

**Comment by ZwerOxotnik** [comment]
@JanSharp, btw, if you have time, could explain/provide info about `debug.getinfo`? It seems like I looked in a wrong way.

**Comment by JanSharp** [comment]
The 2 places in the docs  to look is these:
- https://www.lua.org/manual/5.2/manual.html#pdf-debug.getinfo
- https://www.lua.org/manual/5.2/manual.html#lua_getinfo
it should explain everything but if you don't understand a part feel free to ask

**Comment by ZwerOxotnik** [comment]
```lua
lazyAPI.get_current_mod = function()
	local le = 1
	while debug.getinfo(le, "St") do
	  le = le * 2
	end
	local all_St_info = {}
	for i=1, le do
		all_St_info[tostring(i)] = debug.getinfo(i, "St")
	end
	log(serpent.block(all_St_info))
```
```lua
   1.447 Loading mod assemblyanalyst 1.1.11 (data.lua)
   1.449 Script @__zk-lib__/experimental/lazyAPI.lua:1222: {
  ["1"] = {
    istailcall = false,
    lastlinedefined = 1247,
    linedefined = 1213,
    short_src = "__zk-lib__/experimental/lazyAPI.lua",
    source = "@__zk-lib__/experimental/lazyAPI.lua",
    what = "Lua"
  },
  ["2"] = {
    istailcall = false,
    lastlinedefined = 1078,
    linedefined = 1029,
    short_src = "__zk-lib__/experimental/lazyAPI.lua",
    source = "@__zk-lib__/experimental/lazyAPI.lua",
    what = "Lua"
  },
  ["3"] = {
    istailcall = true,
    lastlinedefined = 0,
    linedefined = 0,
    short_src = "data.pho",
    source = "@data.pho",
    what = "main"
  }
}
   1.450 Script @__zk-lib__/experimental/lazyAPI.lua:1231: stack traceback:
	__zk-lib__/experimental/lazyAPI.lua:1226: in function 'get_current_mod'
	__zk-lib__/experimental/lazyAPI.lua:1055: in function 'extend'
	data.pho:3: in main chunk
	(...tail calls...)
```
```lua
   1.425 Script @__zk-lib__/experimental/lazyAPI.lua:1222: {
  ["1"] = {
    istailcall = false,
    lastlinedefined = 1247,
    linedefined = 1213,
    short_src = "__zk-lib__/experimental/lazyAPI.lua",
    source = "@__zk-lib__/experimental/lazyAPI.lua",
    what = "Lua"
  },
  ["2"] = {
    istailcall = false,
    lastlinedefined = 1078,
    linedefined = 1029,
    short_src = "__zk-lib__/experimental/lazyAPI.lua",
    source = "@__zk-lib__/experimental/lazyAPI.lua",
    what = "Lua"
  },
  ["3"] = {
    istailcall = false,
    lastlinedefined = 0,
    linedefined = 0,
    short_src = "__zk-lib__/data.lua",
    source = "@__zk-lib__/data.lua",
    what = "main"
  }
}
   1.425 Script @__zk-lib__/experimental/lazyAPI.lua:1231: stack traceback:
	__zk-lib__/experimental/lazyAPI.lua:1226: in function 'get_current_mod'
	__zk-lib__/experimental/lazyAPI.lua:1055: in function 'extend'
	__zk-lib__/data.lua:32: in main 
```

**Comment by ZwerOxotnik** [comment]
So, we just need the latest level, right?

**Comment by JanSharp** [comment]
Oh this makes sense now. Tail calls in combination with get info / stack traces are always confusing.
Alright, so, it's saying that `data.pho` was tail called, however that "level" does contain the information about the function that was called. For some reason I thought there'd be like an empty level that just says "yea there was a function here that tail called something" but Lua itself doesn't even keep that information, so that was dumb of me.

Anyway, I believe to achieve what you want all you have to do is remove the `not info.istailcall` from the if condition.

**Comment by JanSharp** [comment]
(and update the comments accordingly ;) )

**Comment by ZwerOxotnik** [comment]
Well, there's more to it for me actually...

**Comment by JanSharp** [comment]
I'm listening, if you want me to assist with it. Otherwise you're free to change the logic of course

**Comment by JanSharp** [comment]
that also works and is what I usually do. I didn't do it in this case because it looked like you wanted optimized code and a binary search is more optimized, although to be honest the stack trace will be so tiny most of the time that you can totally do it with a basic loop like you have right there

**Comment by ZwerOxotnik** [comment]
`debug.getinfo` returns table, so it "pollutes" a lot.

**Comment by JanSharp** [comment]
correct

**Comment by ZwerOxotnik** [comment]
It's too much "garbage" for binary search, also it does use the same function.

**Comment by JanSharp** [comment]
the binary search ends up reducing the amount calls to getinfo, therefore reduces the amount of tables it creates since it checks fewer "levels"

**Comment by ZwerOxotnik** [comment]
oh, hell, I have to check it xD

**Comment by ZwerOxotnik** [comment]
Well, binary search is search, but should fix it now, because it skipped levels xD

**Comment by JanSharp** [comment]
I'm not entirely sure what you mean by that, it skipping levels is intentional, as long as it ultimlately finds the last one. If it doesn't do that then it is bugged, yes, not sure if you meant it like that.

**Comment by ZwerOxotnik** [comment]
Well, it's weird, it should 2 binary searches, because there are several nils in such boundaries.

**Comment by ZwerOxotnik** [comment]
You just found one, but not the first one.

**Comment by ZwerOxotnik** [comment]
It's "bulky" for a small amount of levels.

**Comment by ZwerOxotnik** [comment]
Okay, my explanation is useless, but I'll check again.

**Comment by ZwerOxotnik** [comment]
So, usually binary search for a specific data, but we found just some data, but it's not the latest one.

**Comment by JanSharp** [comment]
I'm sorry, I still don't follow.
The level - the number passed to `debug.getinfo` - starts at 0 (which will be the getinfo function itself) and counts up as you walk up the stack, such that the function calling debug.getinfo will be 1, and the one calling that one is 2 and so on until it reaches the main entry point. In standalone Lua that would be a C function, in factorio it's the main Lua entry point. It is impossible for `debug.getinfo(i)` to return `nil` and `debug.getinfo(i + 1)` to return `~= nil`.

A binary search works by jumping back and forth until it finds the last level that is not nil, and it will never check the same level twice.

In this case it first keeps doubling a number until it returns nil, which will be the upper bound, and it remembers the last one that didn't return nil as a lower bound. Then it takes the median of the two bounds and checks if that one is nil. if it is, it updates the upper bound to that number, if it isn't nil it updates the lower bound. Once there are no more levels between the 2 bounds it knows that the lower bound is the last level that doesn't return nil.

In a worst case scenario the binary search will check every level, but like I said it'll never check the same one twice.

An example:
Imagine the levels were like this:
```
0 - debug.getinfo
1 - count_levels
2 - get_stage
3 - foo
4 - bar
5 - baz
6 - main chunk
```
Then the binary search would check the following levels in this order: 1, 2, 4, 8, 6, 7
As you can see, 8 and 7 were nil, the other 4 weren't. So instead of 6 tables, it only created 4.


If the issue is that the binary search is finding the last one when you don't actually want that one, well, you first have to find the last level before you can start walking down the call stack, which is why I made `get_first_lua_func_info` a separate function

**Comment by ZwerOxotnik** [comment]
The step of binary search depends on mean and the same time we don't know upper limit because we skipped by `n!`

Invalid case: the latest actual valid level is 25, but step is:

x = 25 ("lower limit")

g = x \* 2 ("upper limit")

step = floor((x + g) / 2)

step = 37

The binary search will rise the lower limit, but the valid answer is 25.

**Comment by JanSharp** [comment]
Once again I'm sorry but I don't follow. It sounds to me like you've got a broken binary search.
I hope providing an example sheds some light:
It's using the same binary search algorithm as above, but using a callback function instead of getinfo for testing. I technically changed upper_bound to start 2, it is unneccessary to check for 1 because it always exists.
```lua
local function binary_search(does_level_exist)
  -- this code assumes that level 1 _always_ exists. In another case, the implementation
  -- would have to be different, but this is much easier to understand imo
  local lower_bound = 1
  local upper_bound = 2
  print("initializing lower_bound at 1 and upper_bound at 2")
  -- find an upper bound
  while does_level_exist(upper_bound) do
    print("level "..upper_bound.." does exist, setting lower_bound to "..lower_bound.." and upper_bound to "..upper_bound)
    lower_bound = upper_bound
    upper_bound = upper_bound * 2
  end
  print("level "..upper_bound.." does not exist, proceeding with binary search")
  -- do a binary search
  while lower_bound < (upper_bound - 1) do
    local median = math.floor((lower_bound + upper_bound) / 2)
    if does_level_exist(median) then
      lower_bound = median
      print("level "..median.." does exist, setting lower_bound to "..median)
    else
      upper_bound = median
      print("level "..median.." does not exist, setting upper_bound to "..median)
    end
  end
  return lower_bound
end

print("testing with target 6")
print("result: "..binary_search(function(i) return i <= 6 end))
print()
print("testing with target 28")
print("result: "..binary_search(function(i) return i <= 28 end))
```
output:
```
testing with target 6
initializing lower_bound at 1 and upper_bound at 2
level 2 does exist, setting lower_bound to 1 and upper_bound to 2
level 4 does exist, setting lower_bound to 2 and upper_bound to 4
level 8 does not exist, proceeding with binary search
level 6 does exist, setting lower_bound to 6
level 7 does not exist, setting upper_bound to 7
result: 6

testing with target 28
initializing lower_bound at 1 and upper_bound at 2
level 2 does exist, setting lower_bound to 1 and upper_bound to 2
level 4 does exist, setting lower_bound to 2 and upper_bound to 4
level 8 does exist, setting lower_bound to 4 and upper_bound to 8
level 16 does exist, setting lower_bound to 8 and upper_bound to 16
level 32 does not exist, proceeding with binary search
level 24 does exist, setting lower_bound to 24
level 28 does exist, setting lower_bound to 28
level 30 does not exist, setting upper_bound to 30
level 29 does not exist, setting upper_bound to 29
result: 28
```

**Comment by ZwerOxotnik** [comment]
In short, I should go sleep, otherwise I'll mess even more.

**Comment by JanSharp** [comment]
sorry, I messed that up before copying it over, fixed it

**Comment by ZwerOxotnik** [comment]
it's fine

**Comment by JanSharp** [comment]
have a good sleep, I know how it feels trying to program while tired. There's a high chance of success the next day

**Comment by ZwerOxotnik** [comment]
```lua
local function count_levels()
  local li = 1
  local le = 1
  -- find a possible upper bound
  while debug.getinfo(le, "t") do
    li = le
    le = le * 2
  end

  -- do a binary search
  local m
  while li < le do
    m = (li + le) / 2
    if debug.getinfo(m, "t") then
      li = m
    else
      le = m
    end
  end
  return m
end
```

**Comment by ZwerOxotnik** [comment]
It looks a bit off, but it works (I should check more) and I got used to levels.
```lua
local function find_deepest_level()
	local li = 1
	local le = 1
	-- find a possible upper bound
	while debug.getinfo(le, "t") do
	  li = le
	  le = le * 2
	end

	-- do a binary search
	local m
	while li < le do
	  m = math.floor((li + le) / 2)
	  if debug.getinfo(m, "t") then
		li = m
		if li == m then
			break
		end
	  else
		le = m
	  end
	end

	return m - 1
end
```

**Comment by ZwerOxotnik** [comment]
[https://byjus.com/maths/mean-median-mode/](https://byjus.com/maths/mean-median-mode/) (not the best example, but not the worst)

**Comment by ZwerOxotnik** [comment]
This works fine:

```lua
local function find_deepest_level()
    local li = 1
    local le = 1
    -- find a possible upper bound
    while debug.getinfo(le, "t") do
        li = le
        le = le * 2
    end

    -- do a binary search
    local m
    while li < le do
        m = math.floor((li + le) / 2)
        if debug.getinfo(m, "t") then
            if li == m then
                return m - 1
            else
                li = m
            end
        else
            le = m
        end
    end
end
```

**Comment by ZwerOxotnik** [comment]
Also count\_levels work fine too.

**Comment by ZwerOxotnik** [comment]
So, the misunderstanding appeared because I didn't pay enough attention to get\_first\_lua\_func\_info.

**Comment by ZwerOxotnik** [comment]
It seems like minimal level is 3, but it depends.

**Comment by ZwerOxotnik** [comment]
It seems like minimal level is 2 for count\\\_levels, but it depends.  
```
local function count_levels()  
  local li = 3  
  local le = 2
```

**Comment by JanSharp** [comment]
happy to hear you got it working :+1: 

And I hope you don't mind a little essay, I know I can be a bit verbose :see_no_evil: 

The minimal level ultimately depends on how many tail calls there were. Idk if you know what exactly they are so I'll explain: A tail call happens when you do `return foo()`, which means the the very last instruction before return would be a call, and the return values of the call get returned by this function without modification. That menas `return 1, foo()` cannot be a tail call, neither can `return (foo())` (because it changes the return values by forcing it to be just 1, not multiple).
A tail call means that the calling function's call info (the thing describing which function is currently running) gets reused by the called function. That way it doesn't have to perform a heap allocation for a new call info, however it also means that it'll overwrite the info of the calling function, leaving it with just knowing "this function was tail callled, but we don't know from where", and it's only 1 call info on the stack, not 2. If the tail called function ends up tail calling another one the same thing happens, which means it doesn't even know how many calls were leading up to the currently running tail called function.

For getinfo that means that these tail call chains appear as a single level, with information about the last tail called function, and a flag indicating that it was tail called.
So now that we know what tail calls are and how they behave, imagine a scenario where the main chunk - like `data.lua` - ended with a statement like `return data:extend{--[[...]]}`. Well, that's a tail call. Then imagine that all calls leading up to `count_levels` also were tail calls, which in this case doesn't make sense but we'll explore it just for the theory. That would mean that `count_levels` is the only function on the call stack as its call info kept getting reused and overwritten. Note that C functions cannot be tailcalled, so the call to getinfo will always create a new call info. So in this theoretical scenario we would only have 2 levels. Level 0 being getinfo, and level 1 being count_levels, the rest were tail calls.

In reality the calls to `count_levels` and `get_first_lua_func_info` never are tail calls, so the bare minimum you can get is this:
- 0: getinfo
- 1: count_levels
- 2: get_first_lua_func_info
- 3: get_stage or get_current_mod

Where all calls leading up to `get_stage` or `get_current_mod` were tail calls, which also doesn't make sense since nobody would call those 2 functions as the last thing in their main chunk, but even if it doesn't make sense, it is the lowest count possible

**Comment by ZwerOxotnik** [comment]
Briefly about count\_levels etc., it works ~6 times faster at least, than relying on the debug.traceback etc. My cashed variant is even slower for this case and has some bugs.

All bugs have been fixed: ZwerOxotnik/zk-lib@093de38, ZwerOxotnik/zk-factorio-static-lib@4a9755f

**Comment by JanSharp** [comment]
Wonderful to hear, I'm pleasently surprised that this is actually faster, goes to show that string operations are slow and Lua's speed is not to be underestimated once again :D

I also appreciate the attributions and I am happy to have helped :+1:

**Comment by ZwerOxotnik** [comment]
@JanSharp, btw, I have been doing some experiments, optimization etc., but most importantly, `debug.getinfo(li, "")` works fine.

**Comment by JanSharp** [comment]
Oh I didn't know that it would accept an empty string, always assumed it would require at least 1 letter. That's good to know, it'll just return an emtpy table then
